

// This is a manually written route tree for the prototype.
// In production, this would be generated by @tanstack/router-plugin.

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRoute } from './routes/index'
import { Route as UploadRoute } from './routes/upload'
import { Route as VerifyJobIdRoute } from './routes/verify.$jobId'
import { Route as DashboardRoute } from './routes/dashboard'
import { Route as AlertsRoute } from './routes/alerts'
import { Route as LoginRoute } from './routes/login'

const root = rootRoute.addChildren([
  IndexRoute,
  UploadRoute,
  VerifyJobIdRoute,
  DashboardRoute,
  AlertsRoute,
  LoginRoute,
])

export const routeTree = root
